// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-courses.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_courses_default = defineTool({
  name: "list_courses",
  title: "List mastery tracks",
  description: "List the signed-in user's mastery tracks (courses) with id, name, code, color, semester and professor info.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("courses").select("id,name,code,color,semester,credits,professor_name").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { courses: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-syllabus-events.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_syllabus_events_default = defineTool2({
  name: "list_syllabus_events",
  title: "List calendar events",
  description: "List syllabus/calendar milestones for the signed-in user. Filter by course_id and by time window (upcoming, past, or all).",
  inputSchema: {
    course_id: z.string().uuid().optional().describe("Optional course id to filter by."),
    window: z.enum(["upcoming", "past", "all"]).default("upcoming").describe("Time window relative to today."),
    limit: z.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ course_id, window, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb2(ctx).from("syllabus_dates").select("id,title,date,event_type,is_high_stakes,course_id").limit(limit);
    if (course_id) q = q.eq("course_id", course_id);
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    if (window === "upcoming") q = q.gte("date", today).order("date", { ascending: true });
    else if (window === "past") q = q.lt("date", today).order("date", { ascending: false });
    else q = q.order("date", { ascending: true });
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { events: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-syllabus-event.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_syllabus_event_default = defineTool3({
  name: "create_syllabus_event",
  title: "Create calendar event",
  description: "Create a milestone / calendar event (exam, assignment, quiz, etc.) for the signed-in user.",
  inputSchema: {
    title: z2.string().trim().min(1).max(200),
    date: z2.string().describe("ISO date YYYY-MM-DD."),
    event_type: z2.string().trim().min(1).max(50).default("assignment").describe("e.g. exam, assignment, quiz, project, reading."),
    course_id: z2.string().uuid().optional(),
    is_high_stakes: z2.boolean().default(false)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async ({ title, date, event_type, course_id, is_high_stakes }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb3(ctx).from("syllabus_dates").insert({ title, date, event_type, course_id: course_id ?? null, is_high_stakes, user_id: ctx.getUserId() }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Created event: ${data.title} on ${data.date}` }], structuredContent: { event: data } };
  }
});

// src/lib/mcp/tools/list-study-sessions.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_study_sessions_default = defineTool4({
  name: "list_study_sessions",
  title: "List focus sessions",
  description: "List the signed-in user's recent focus/study sessions with duration, mode, focus score and optional course link.",
  inputSchema: {
    course_id: z3.string().uuid().optional(),
    limit: z3.number().int().min(1).max(200).default(25)
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ course_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb4(ctx).from("study_sessions").select("id,course_id,mode,duration_minutes,focus_score,commit_message,completed_at").order("completed_at", { ascending: false }).limit(limit);
    if (course_id) q = q.eq("course_id", course_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { sessions: data ?? [] } };
  }
});

// src/lib/mcp/tools/log-study-session.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var log_study_session_default = defineTool5({
  name: "log_study_session",
  title: "Log a focus session",
  description: "Record a completed focus/study session for the signed-in user.",
  inputSchema: {
    duration_minutes: z4.number().int().min(1).max(600),
    mode: z4.string().trim().min(1).max(50).default("focus").describe("e.g. focus, review, deep-work."),
    focus_score: z4.number().int().min(1).max(5).optional(),
    commit_message: z4.string().trim().max(500).optional().describe("What you worked on."),
    course_id: z4.string().uuid().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb5(ctx).from("study_sessions").insert({
      user_id: ctx.getUserId(),
      duration_minutes: input.duration_minutes,
      mode: input.mode,
      focus_score: input.focus_score ?? null,
      commit_message: input.commit_message ?? null,
      course_id: input.course_id ?? null,
      completed_at: (/* @__PURE__ */ new Date()).toISOString()
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Logged ${data.duration_minutes}m ${data.mode} session.` }], structuredContent: { session: data } };
  }
});

// src/lib/mcp/tools/get-365-stats.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
function sb6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function computeStreak(dates) {
  const set = new Set(dates);
  let streak = 0;
  const d = /* @__PURE__ */ new Date();
  if (!set.has(d.toISOString().slice(0, 10))) d.setDate(d.getDate() - 1);
  while (set.has(d.toISOString().slice(0, 10))) {
    streak++;
    d.setDate(d.getDate() - 1);
  }
  return streak;
}
var get_365_stats_default = defineTool6({
  name: "get_365_stats",
  title: "365 Challenge stats",
  description: "Return the signed-in user's 365-day consistency stats: total days completed, current streak, percent progress, and today's completion status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb6(ctx).from("daily_completions").select("completed_date").order("completed_date", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const dates = (data ?? []).map((r) => r.completed_date);
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const stats = {
      total_completed: dates.length,
      current_streak: computeStreak(dates),
      percent: Math.round(dates.length / 365 * 1e3) / 10,
      completed_today: dates.includes(today)
    };
    return {
      content: [{ type: "text", text: `${stats.total_completed}/365 days \xB7 streak ${stats.current_streak} \xB7 today ${stats.completed_today ? "done" : "not yet"}` }],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/tools/complete-today.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
function sb7(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var complete_today_default = defineTool7({
  name: "complete_today",
  title: "Mark today complete",
  description: "Mark today as complete in the 365-Day Consistency Challenge for the signed-in user. Idempotent for the same day.",
  inputSchema: {},
  annotations: { readOnlyHint: false, idempotentHint: true, destructiveHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const client = sb7(ctx);
    const existing = await client.from("daily_completions").select("id").eq("completed_date", today).maybeSingle();
    if (existing.data) {
      return { content: [{ type: "text", text: `Already completed for ${today}.` }], structuredContent: { completed_date: today, already: true } };
    }
    const { error } = await client.from("daily_completions").insert({ user_id: ctx.getUserId(), completed_date: today });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Marked ${today} complete.` }], structuredContent: { completed_date: today, already: false } };
  }
});

// src/lib/mcp/tools/get-daily-note.ts
import { createClient as createClient8 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^4.4.3";
function sb8(ctx) {
  return createClient8(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_daily_note_default = defineTool8({
  name: "get_daily_note",
  title: "Read a daily note",
  description: "Read the signed-in user's daily note for a specific date (defaults to today).",
  inputSchema: {
    date: z5.string().optional().describe("ISO date YYYY-MM-DD. Defaults to today.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const d = date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await sb8(ctx).from("daily_notes").select("id,note_date,note_text,updated_at").eq("note_date", d).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: data?.note_text ?? "(no note)" }], structuredContent: { note: data, date: d } };
  }
});

// src/lib/mcp/tools/set-daily-note.ts
import { createClient as createClient9 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^4.4.3";
function sb9(ctx) {
  return createClient9(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var set_daily_note_default = defineTool9({
  name: "set_daily_note",
  title: "Write a daily note",
  description: "Create or overwrite the signed-in user's daily note for a specific date (defaults to today).",
  inputSchema: {
    note_text: z6.string().trim().min(1).max(1e4),
    date: z6.string().optional().describe("ISO date YYYY-MM-DD. Defaults to today.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, destructiveHint: false },
  handler: async ({ note_text, date }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const d = date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const client = sb9(ctx);
    const existing = await client.from("daily_notes").select("id").eq("note_date", d).maybeSingle();
    if (existing.data) {
      const { data: data2, error: error2 } = await client.from("daily_notes").update({ note_text }).eq("id", existing.data.id).select().single();
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      return { content: [{ type: "text", text: `Updated note for ${d}.` }], structuredContent: { note: data2 } };
    }
    const { data, error } = await client.from("daily_notes").insert({ user_id: ctx.getUserId(), note_date: d, note_text }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Saved note for ${d}.` }], structuredContent: { note: data } };
  }
});

// src/lib/mcp/tools/list-published-courses.ts
import { createClient as createClient10 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.23.0";
function sb10(ctx) {
  return createClient10(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_published_courses_default = defineTool10({
  name: "list_published_courses",
  title: "Browse MatrixMindset catalog",
  description: "List all courses published by MatrixMindset admins in the public catalog (title, price, duration, description).",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb10(ctx).from("admin_courses").select("id,title,description,price,duration,image_url").eq("is_published", true).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { courses: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nhttxgiskwvykwcymbsw";
var mcp_default = defineMcp({
  name: "matrixmindset-mcp",
  title: "MatrixMindset",
  version: "0.1.0",
  instructions: "Tools for the MatrixMindset study platform. Read and update the signed-in user's mastery tracks (courses), syllabus/calendar events, focus sessions, daily notes, and the 365-day consistency challenge. Also browse the public course catalog.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_courses_default,
    list_syllabus_events_default,
    create_syllabus_event_default,
    list_study_sessions_default,
    log_study_session_default,
    get_365_stats_default,
    complete_today_default,
    get_daily_note_default,
    set_daily_note_default,
    list_published_courses_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
